linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  lll:
    line-length: 140

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet

issues:
  exclude-dirs:
    - vendor
  exclude-use-default: false

run:
  tests: true
  timeout: 5m
  deadline: 5m
  issues-exit-code: 1
  concurrency: 4 